# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('src', 'src'),
    ],
    hiddenimports=[
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'src.assets.convertor',
        'src.assets.update_file',
        'src.assets.transform_string',
        'src.assets.reorder',
        'src.assets.rename_files',
        'src.assets.count_files_in_directory',
        'src.assets.is_image',
        'src.uiitems.close_button',
        'src.uiitems.blink_button',
        'src.uiitems.text_box',
        'src.uiitems.preview_box',
        'src.uiitems.notification_bar',
        'src.uiitems.file_input',
        'src.uiitems.dash_line',
        'src.uiitems.custom_alert',
        'src.uiitems.collapsible_box',
        'src.widgets.drag_drop',
        'src.widgets.initiation_files_input',
        'src.widgets.img_resizer',
        'src.widgets.img_renamer',
        'src.widgets.select_initiation_csv',
        'src.widgets.login',
        'PIL',
        'PIL.Image',
        'PIL.ImageOps',
        'dotenv',
        'glob',
        'pathlib',
        'dataclasses',
        'enum',
        'datetime',
        'logging',
        're',
        'typing',
        'os',
        'sys',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TinyGIFApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/favicon.ico',
) 